<?php
/**
 * thoitiet
 *
 * @copyright Copyright © 2020 Staempfli AG. All rights reserved.
 * @author    juan.alonso@staempfli.com
 */


?>
<!DOCTYPE html>
<html>
<head>
    <title>Tin tức thời tiết</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<?php
date_default_timezone_set("Asia/Ho_Chi_Minh");
$cityID = "1581130";
$apiKey = "4b5184758065fd5034513224557d1abd";
$googleApiUrl = "http://api.openweathermap.org/data/2.5/weather?id=".$cityID."&lang=vi&units=metric&APPID=".$apiKey;
$ch = curl_init();
curl_setopt($ch,CURLOPT_HEADER,0);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch,CURLOPT_URL,$googleApiUrl);
curl_setopt($ch,CURLOPT_FOLLOWLOCATION,1);
curl_setopt($ch,CURLOPT_VERBOSE,0);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
$response = curl_exec($ch);
curl_close($ch);
$data = json_decode($response);
$currentTime = time();
?>
<div class="report-container">
    <h2>Thời tiết <?php echo $data->name;?></h2>
    <div class="time">
        <div><?php echo date("l g:i A",$currentTime);?></div>
        <div><?php echo date("jS F, Y",$currentTime);?></div>
        <div><?php echo ucwords($data->weather[0]->description);?></div>
    </div>
    <div class="weather-forecast">
        <img
            src="http://openweathermap.org/img/w/<?php echo $data->weather[0]->icon;?>.png"
            class="weather-icon" /> <?php echo $data->main->temp_max; ?>&deg;C<span
            class="min-temperature"><?php echo $data->main->temp_min; ?>&deg;C</span>
    </div>
    <div class="time">
        <div>
            Độ ẩm: <?php echo $data->main->humidity;?>%
        </div>
        <div>
            Tốc độ gió: <?php echo $data->wind->speed;?>km/h
        </div>

    </div>

</div>
</body>
</html>
